### ISSUE TITLE
Revised Binary Badges.

### ISSUE THREAD

**Issue by virgil** [seansaito/Roster#15]
As-is, there are checkmarks for "positive binary things", see below.
<img width="519" alt="screen shot 2016-02-03 at 02 38 50" src="https://cloud.githubusercontent.com/assets/81322/12760044/67b5a760-ca1f-11e5-92c3-8ea6a6eab2c0.png">

These should be badges.  I suppose just make them black badges such that when you hover over them it says what the badge is for.  For example, if you hover over the "up to date" badge, the tooltip will say, "Runs Recommended Tor Version For All Relays".

**Comment by seansaito** [comment]
All badges now have tooltips
