### ISSUE TITLE
bug in exit probabliity?

### ISSUE THREAD

**Issue by virgil** [seansaito/Roster#6]
See: http://www.tor-roster.org/family_detail/B9B927347E005256D5D48007C38208FE8F7CC3BE

This family has  92.34 percentile for Exit bandwidth, yet has 0.000% for Exit Probability?

**Comment by seansaito** [comment]
I believe that is because 92% of families dont have exit relays

**Comment by virgil** [comment]
Then I suppose the exit badge should only be considered for the subpopulation relays that have the "exit" flag.  Should be impossible to get an exit-bandwidth badge without being an exit ;)

**Comment by seansaito** [comment]
Agreed.
