### ISSUE TITLE
Occassional HTTP 500 errors

### ISSUE THREAD

**Issue by virgil** [seansaito/Roster#7]
Maybe about 10% of the time I click to a tor-roster.org URL I get an Error 500.  And when I don't get an Error 500 it seems to take a while for it to load?  What's the problem?  I presume it's some sort of backend thing.  Should Roster run its own instance of Onionoo?  Alternatively, does some kind of caching need to be implemented?  I'm happy to pay for caching via Fastly/CloudFlare.

**Comment by seansaito** [comment]
Let me play with Apache caching

**Comment by virgil** [comment]
You can run Heroku stuff locally with:

https://devcenter.heroku.com/articles/getting-started-with-python#run-the-app-locally

Sounds easier than Apache.

**Comment by seansaito** [comment]
I think making connections to S3 occasionally caused errors. So hopefully the transition to local static files would prevent these from happening.

**Comment by seansaito** [comment]
Anymore now? Otherwise I will close the issue.

**Comment by virgil** [comment]
Close it.
